import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import api from '../api/api';
import { FileText, Database, Globe, Terminal, Copy, Check, FolderTree, FileCode, ListTodo, Loader2, Sparkles } from 'lucide-react';
import Button from '../components/ui/Button';

export default function PublicProjectView() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [project, setProject] = useState<any>(null);
  const [activeTab, setActiveTab] = useState('readme');
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    fetchPublicProject();
  }, [id]);

  const fetchPublicProject = async () => {
    try {
      const res = await api.get(`/projects/public/${id}`);
      setProject(res.data);
    } catch (err) {
      console.error('Failed to fetch public project');
      navigate('/');
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    const content = tabs.find(t => t.id === activeTab)?.content;
    if (content) {
      navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  if (loading) return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center font-bold text-gray-400">
      <Loader2 className="animate-spin mr-2" /> Loading Public Preview...
    </div>
  );

  if (!project) return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center font-bold text-red-400">
      Oops! This project is no longer public or doesn't exist.
    </div>
  );

  const tabs = [
    { id: 'readme', label: 'README.md', icon: <FileText size={18} />, content: project.readme },
    { id: 'api', label: 'API Docs', icon: <Terminal size={18} />, content: project.apiDocs },
    { id: 'structure', label: 'Folder Structure', icon: <FolderTree size={18} />, content: project.folderStructure },
    { id: 'env', label: '.env Template', icon: <FileCode size={18} />, content: project.envTemplate },
    { id: 'postman', label: 'Postman', icon: <ListTodo size={18} />, content: project.postmanCollection },
    { id: 'db', label: 'DB Schema', icon: <Database size={18} />, content: project.dbSchema },
    { id: 'deployment', label: 'Deployment', icon: <Globe size={18} />, content: project.deploymentGuide },
    { id: 'landing', label: 'Landing Page', icon: <Globe size={18} />, content: project.landingPage },
  ];

  const currentTab = tabs.find(t => t.id === activeTab);
  const currentContent = currentTab?.content || 'Content not available.';

  return (
    <div className="min-h-screen bg-gray-50 pb-20">
      {/* Public Header */}
      <nav className="bg-white border-b border-gray-100 py-4 px-8 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-3">
             <div className="w-10 h-10 bg-brand-primary rounded-xl flex items-center justify-center text-white font-black shadow-lg shadow-brand-primary/20">
                A
             </div>
             <span className="text-lg font-black tracking-tighter text-gray-900">AutoDev <span className="text-brand-primary">AI</span></span>
             <span className="px-2 py-0.5 bg-gray-100 text-[10px] font-black uppercase tracking-widest text-gray-400 rounded-md">Shared Preview</span>
          </div>
          <Button onClick={() => navigate('/register')} className="px-6 py-2 rounded-xl text-sm font-black">Get Started for Free</Button>
        </div>
      </nav>

      <div className="max-w-6xl mx-auto mt-12 px-6 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
        <header className="bg-white p-10 rounded-[3rem] border border-gray-100 shadow-sm flex flex-col md:flex-row justify-between items-center gap-8">
          <div className="text-center md:text-left">
            <h1 className="text-4xl font-black text-gray-900 tracking-tight">{project.title}</h1>
            <p className="text-gray-500 mt-2 font-medium max-w-2xl">{project.input}</p>
          </div>
          <div className="flex gap-4">
             <Button variant="secondary" onClick={handleCopy} className="rounded-2xl px-6 py-3.5 font-bold flex items-center gap-2">
                {copied ? <Check size={18} className="text-green-600" /> : <Copy size={18} />}
                {copied ? 'Copied!' : 'Copy Asset'}
             </Button>
             <div className="flex items-center gap-2 px-6 py-3.5 bg-brand-primary/5 text-brand-primary rounded-2xl font-black text-sm">
                <Sparkles size={18} /> Generated by AI
             </div>
          </div>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
           {/* Sidebar */}
           <div className="lg:col-span-1 space-y-2">
              <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-4 px-4">Architecture Assets</p>
              {tabs.map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`w-full flex items-center gap-3 px-5 py-4 rounded-2xl transition-all font-bold text-sm ${
                    activeTab === tab.id
                      ? 'bg-brand-primary text-white shadow-xl shadow-brand-primary/10'
                      : 'text-gray-500 hover:bg-white hover:text-gray-900 border border-transparent hover:border-gray-100'
                  }`}
                >
                  {tab.icon}
                  {tab.label}
                </button>
              ))}
           </div>

           {/* Content */}
           <div className="lg:col-span-3 bg-white rounded-[2.5rem] border border-gray-100 shadow-sm overflow-hidden min-h-[600px] flex flex-col relative group">
              <div className="bg-gray-50/50 px-8 py-4 border-b border-gray-100/50 flex justify-between items-center">
                <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest font-mono">{currentTab?.label}</span>
              </div>
              <div className="flex-1 p-8 font-mono text-sm overflow-auto custom-scrollbar">
                  <pre className="text-gray-800 leading-relaxed whitespace-pre-wrap animate-in fade-in duration-500">
                    {currentContent}
                  </pre>
              </div>
           </div>
        </div>
      </div>
    </div>
  );
}
